### ISSUE TITLE
Release 1.2.115 badarith error after make

### ISSUE THREAD

**Issue by Crash0v3r1de** [helium/blockchain-http#374] opened 2021-12-08 22:06 UTC
Booting up an ETL and http to do my own calls however after my ETL is up and doing it's thing whenever I make any calls to my http API it throws:

`15:01:26.126 [error] error: badarith`

Absolutely nothing in the log files, DB user accounts working fine so not really sure the issue. Did not pull the latest github since it's build is failing.

Ubuntu 20.04

**Comment by madninja** [comment] 2021-12-09 08:53
What do you mean by “etl is doing its thing”? How high is the Postgres blocks table height? The http workers won’t work with an etl that has little to no stored data

**Comment by madninja** [comment] 2021-12-13 14:42
Please provide log details from console.log with details of this error. I'm not able to reproduce it. 

Closing for now but will re-open if you still have the issues and more details are provided

**Closed by madninja** 2021-12-13 14:42 UTC
